package com.rent.cab.entity;

// Generated Jan 11, 2014 12:15:42 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Cab generated by hbm2java
 */
@Entity
@Table(name = "cab", catalog = "rendacab")
public class Cab implements java.io.Serializable {

	private Long cabId;
	private String cabRegisterationNumber;
	private String cabModel;
	private String cabMake;
	private Set<CabService> cabServices = new HashSet<CabService>(0);

	public Cab() {
	}

	public Cab(String cabRegisterationNumber, String cabModel, String cabMake) {
		this.cabRegisterationNumber = cabRegisterationNumber;
		this.cabModel = cabModel;
		this.cabMake = cabMake;
	}

	public Cab(String cabRegisterationNumber, String cabModel, String cabMake,
			Set<CabService> cabServices) {
		this.cabRegisterationNumber = cabRegisterationNumber;
		this.cabModel = cabModel;
		this.cabMake = cabMake;
		this.cabServices = cabServices;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "cab_id", unique = true, nullable = false)
	public Long getCabId() {
		return this.cabId;
	}

	public void setCabId(Long cabId) {
		this.cabId = cabId;
	}

	@Column(name = "cab_registeration_number", nullable = false, length = 100)
	public String getCabRegisterationNumber() {
		return this.cabRegisterationNumber;
	}

	public void setCabRegisterationNumber(String cabRegisterationNumber) {
		this.cabRegisterationNumber = cabRegisterationNumber;
	}

	@Column(name = "cab_model", nullable = false, length = 100)
	public String getCabModel() {
		return this.cabModel;
	}

	public void setCabModel(String cabModel) {
		this.cabModel = cabModel;
	}

	@Column(name = "cab_make", nullable = false, length = 100)
	public String getCabMake() {
		return this.cabMake;
	}

	public void setCabMake(String cabMake) {
		this.cabMake = cabMake;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cab")
	public Set<CabService> getCabServices() {
		return this.cabServices;
	}

	public void setCabServices(Set<CabService> cabServices) {
		this.cabServices = cabServices;
	}

}
