package com.rent.cab.entity;

// Generated Jan 11, 2014 12:15:42 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name = "users", catalog = "rendacab")
public class Users implements java.io.Serializable {

	private Long userId;
	private String userName;
	private String password;
	private String email;
	private String contactNumber;
	private Set<UserRoles> userRoleses = new HashSet<UserRoles>(0);
	private Set<CabService> cabServices = new HashSet<CabService>(0);
	private Set<UserLocations> userLocationses = new HashSet<UserLocations>(0);

	public Users() {
	}

	public Users(String userName, String password, String email,
			String contactNumber) {
		this.userName = userName;
		this.password = password;
		this.email = email;
		this.contactNumber = contactNumber;
	}

	public Users(String userName, String password, String email,
			String contactNumber, Set<UserRoles> userRoleses,
			Set<CabService> cabServices, Set<UserLocations> userLocationses) {
		this.userName = userName;
		this.password = password;
		this.email = email;
		this.contactNumber = contactNumber;
		this.userRoleses = userRoleses;
		this.cabServices = cabServices;
		this.userLocationses = userLocationses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "user_id", unique = true, nullable = false)
	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	@Column(name = "user_name", nullable = false, length = 200)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "password", nullable = false, length = 200)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "email", nullable = false, length = 200)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "contact_number", nullable = false, length = 100)
	public String getContactNumber() {
		return this.contactNumber;
	}

	public void setContactNumber(String contactNumber) {
		this.contactNumber = contactNumber;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "users")
	public Set<UserRoles> getUserRoleses() {
		return this.userRoleses;
	}

	public void setUserRoleses(Set<UserRoles> userRoleses) {
		this.userRoleses = userRoleses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "users")
	public Set<CabService> getCabServices() {
		return this.cabServices;
	}

	public void setCabServices(Set<CabService> cabServices) {
		this.cabServices = cabServices;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "users")
	public Set<UserLocations> getUserLocationses() {
		return this.userLocationses;
	}

	public void setUserLocationses(Set<UserLocations> userLocationses) {
		this.userLocationses = userLocationses;
	}

}
