package com.rent.cab.entity;

// Generated Jan 11, 2014 12:15:42 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UserLocations generated by hbm2java
 */
@Entity
@Table(name = "user_locations", catalog = "rendacab")
public class UserLocations implements java.io.Serializable {

	private Long userLocationId;
	private Users users;
	private Locations locations;

	public UserLocations() {
	}

	public UserLocations(Users users, Locations locations) {
		this.users = users;
		this.locations = locations;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "user_location_id", unique = true, nullable = false)
	public Long getUserLocationId() {
		return this.userLocationId;
	}

	public void setUserLocationId(Long userLocationId) {
		this.userLocationId = userLocationId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "location_id", nullable = false)
	public Locations getLocations() {
		return this.locations;
	}

	public void setLocations(Locations locations) {
		this.locations = locations;
	}

}
